### ISSUE TITLE
Enhanced `ValueError` messages

### ISSUE THREAD

**Issue by romainfd** [pasqal-io/Pulser#148]
When using values out of range (examples below for qubit positions and pulse detuning), the `ValueError` exception could indicate the minimum/maximum authorized value to make fixing the issue faster. The value is used in the test just above so printing it looks easy at first glance.

- Illustration for min qubits distance
![image](https://user-images.githubusercontent.com/32517197/117842634-6aa8c180-b27e-11eb-907a-dc4842225388.png)

- Illustration for max pulse detuning
![image](https://user-images.githubusercontent.com/32517197/117842658-6f6d7580-b27e-11eb-886f-74bf4007e33b.png)

**Comment by LaurentAjdnik** [comment]
Hi! I've been doing so for the new functions `Register.hexagon()` and `Register.max_connectivity()` (soon to be PR-ed), so I might just as well continue for others.

Fortunately, some of them already do, like `Channel.validate_duration()` for instance.

Anyhow, this will be a good opportunity to:
* Make sure allowed values are always mentioned as part of Error messages
* Harmonize the way they are included in strings (throughout the code, you'll find F-strings, `.format()` and perhaps others)

By the way, I found almost no checks for `None` on parameters. Testing against allowed values will result in a TypeError (see [Ordering comparisons](https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons)).

Do we want to add checks and throw an explicit ValueError with a message rather than this default behavior ? This is already the case in `Register.draw()`, `SimulationResults.sample_final_state()` and `Variable.build()` but nowhere else.

**Comment by HGSilveri** [comment]
@LaurentAjdnik thanks! I agree with your suggestions, although I think it would be better to do them in a separate PR if possible, otherwise the one you're currently working on might get too big. 

Regarding checks for `None` on parameters, those do sound a bit of overkill to me, but I will accept them if you feel they are necessary.

**Comment by LaurentAjdnik** [comment]
@HGSilveri: You can assign this one to me, as it is related to #157.

**Comment by LaurentAjdnik** [comment]
> @LaurentAjdnik If you're satisfied with the changes from your last PR, I'll close this, just let me know.

Yup, let's close this one. We might PR a few adjustments in the future but no need to keep this issue open.
