### ISSUE TITLE
Register ids type change after serialization and deserialization

### ISSUE THREAD

**Issue by CdeTerra** [pasqal-io/Pulser#380]
When using numbers as atom ids, they are converted to strings when going through the serialization and deserialization. The consequence is that the outcome will differ from the original value.

For example:

```python
from pulser.register import Register
reg = Register(dict(enumerate([(2,3),(5,1),(10,0)])))
j=json.dumps(reg, cls=PulserEncoder)
r=json.loads(j, cls=PulserDecoder)
assert reg == r # raises because ids do not have the same types
```

This is due to json converting object ids to strings. This might lead to undesired behaviors, because we never know what consequences we might meet by having strings instead of integers for the ids.

I can find two solutions:

- either fix this type change by replacing the json objects with json lists, where the first element would represent the id: this way, the type will be kept
- or systmetically convert int ids to strings, even when not using serialization: the behavior with or without encoding/decoding will be identical

**Comment by HGSilveri** [comment]
I think the idea of having all qubit IDs be strings is worth considering, since this is not the first time this has posed problems. 

However, I think it is not something that can be done quickly, so as a fast workaround I propose we change the `BaseRegister._to_dict()` method to use the `from_coordinates()` classmethod upon deserialization. This will allow the qubit ids to be stored in a list, so they will keep their type in serialization-deserialization roundtrip.
