### ISSUE TITLE
Add an error when a `Channel` is called with an `eom_config` but without a `modulation bandwidth`

### ISSUE THREAD

**Issue by a-corni** [pasqal-io/Pulser#497]
No error is raised when a `Channel` is called with an `eom_config` but without a `modulation bandwidth`.
This is currently only the case for a `Rydberg` channel. It should be generalized to all channels.

**Comment by atomgardner** [comment]
Oh—it looks like I was beaten to the punch by @dakk. @HGSilveri, I'll be sure to follow the CONTRIUTING.md advice in future :smile:

**Comment by HGSilveri** [comment]
Hi @dakk and @atomgardner ! First off, thank you both for your contributions 😄 
Since you both have identical changes and failing CI tests, we have decided to give the prize to the one who gets all CI tests passing first!

@atomgardner : For the sake of fairness, note that @a-corni already gave @dakk some hints on how to fix his failing tests.

**Comment by a-corni** [comment]
Thank you both for your contributions ! @dakk could you please comment here such that I can assign you the issue ?

**Comment by dakk** [comment]
> Thank you both for your contributions ! @dakk could you please comment here such that I can assign you the issue ?

Sure!

**Comment by a-corni** [comment]
Thank you @dakk and @atomgardner for your participation ! I am looking forward seeing your contributions to other issues !
